type Method = 'get' | 'post' | 'put' | 'patch' | 'delete'

const PUBLIC = new Set(['POST /auth/login', 'POST /auth/refresh', 'POST /auth/forgot-password', 'POST /auth/reset-password', 'GET /auth/demo-accounts'])

const ROUTES: Array<[Method, string, string]> = [
  ['get', '/auth/demo-accounts', 'Synthetic demo accounts for the sign-in page'],
  ['post', '/auth/login', 'Login (rate limited)'],
  ['post', '/auth/refresh', 'Rotate refresh token'],
  ['post', '/auth/forgot-password', 'Create a password reset token'],
  ['post', '/auth/reset-password', 'Reset password with a token'],
  ['post', '/auth/logout', 'Logout and revoke the refresh token'],
  ['get', '/auth/me', 'Current user and permissions'],
  ['get', '/dashboard/overview', 'Overview page metrics (single source of truth)'],
  ['get', '/dashboard/summary', 'Dashboard aggregates'],
  ['get', '/dashboard/volume', 'Transaction volume series'],
  ['get', '/dashboard/outcomes', 'Transaction outcome breakdown'],
  ['get', '/realtime/snapshot', 'Live metrics snapshot used after socket reconnect'],
  ['get', '/transactions', 'Paginated, filtered transactions'],
  ['get', '/transactions/export', 'CSV export of filtered transactions'],
  ['get', '/transactions/{id}', 'Transaction detail with lifecycle timeline'],
  ['post', '/transactions/{id}/investigate', 'Record a transaction investigation'],
  ['get', '/institutions', 'Institutions with derived health'],
  ['get', '/institutions/{id}', 'Institution detail'],
  ['get', '/services', 'Monitored services'],
  ['get', '/services/map', 'Service dependency map with impact'],
  ['get', '/system/health', 'System health'],
  ['get', '/system/infrastructure', 'Demo infrastructure metrics (measured vs simulated)'],
  ['get', '/apis', 'API endpoint observability (P50/P95/P99, error rate)'],
  ['get', '/apis/{id}', 'API endpoint detail'],
  ['get', '/incidents', 'Incidents'],
  ['post', '/incidents', 'Create incident'],
  ['get', '/incidents/{id}', 'Incident detail with timeline and RCA'],
  ['patch', '/incidents/{id}', 'Update incident details'],
  ['post', '/incidents/{id}/status', 'Move incident through its lifecycle'],
  ['post', '/incidents/{id}/assign', 'Assign incident'],
  ['post', '/incidents/{id}/severity', 'Change severity'],
  ['post', '/incidents/{id}/notes', 'Add investigation note'],
  ['post', '/incidents/{id}/resolve', 'Resolve incident'],
  ['post', '/incidents/{id}/reopen', 'Reopen incident'],
  ['post', '/incidents/{id}/rca', 'Re-run root cause analysis'],
  ['get', '/anomalies', 'Operational anomalies'],
  ['get', '/anomalies/{id}', 'Anomaly detail with evidence'],
  ['patch', '/anomalies/{id}', 'Confirm, dismiss or resolve an anomaly'],
  ['get', '/analytics', 'Analytics'],
  ['get', '/analytics/overview', 'Analytics overview'],
  ['get', '/analytics/merchants', 'Merchant analytics'],
  ['get', '/analytics/payments', 'Payment method analytics'],
  ['get', '/reports', 'Reports'],
  ['post', '/reports', 'Generate report'],
  ['get', '/reports/schedules', 'Report schedules'],
  ['put', '/reports/schedules/{cadence}', 'Enable or disable a schedule'],
  ['get', '/reports/{id}', 'Report view'],
  ['get', '/reports/{id}/download', 'Download PDF, CSV, or Excel'],
  ['delete', '/reports/{id}', 'Delete report'],
  ['get', '/reconciliation', 'Reconciliation runs and summary'],
  ['post', '/reconciliation/run', 'Run reconciliation'],
  ['get', '/reconciliation/{id}', 'Reconciliation run with mismatch items'],
  ['patch', '/reconciliation/{id}', 'Mark run investigating or resolved'],
  ['get', '/settlements', 'Settlement batches'],
  ['get', '/jobs', 'Operational job runs'],
  ['post', '/jobs/{type}/run', 'Trigger an EOD/BOD job'],
  ['get', '/jobs/{id}', 'Job run detail'],
  ['get', '/data-quality', 'Data quality checks'],
  ['post', '/data-quality/scan', 'Run all data quality checks'],
  ['get', '/data-quality/{id}/records', 'Records behind a data quality issue'],
  ['patch', '/data-quality/{id}', 'Update data quality issue status'],
  ['get', '/audit-logs', 'Audit logs'],
  ['get', '/audit-logs/export', 'CSV export of audit logs'],
  ['get', '/notifications', 'Notifications'],
  ['patch', '/notifications/{id}/read', 'Mark notification read'],
  ['post', '/notifications/read-all', 'Mark all notifications read'],
  ['get', '/users', 'Users'],
  ['get', '/engineers', 'Assignable users'],
  ['post', '/users', 'Create user'],
  ['patch', '/users/{id}', 'Update user, role or status'],
  ['post', '/users/{id}/reset-password', 'Reset a user password'],
  ['get', '/settings', 'Settings'],
  ['patch', '/settings/profile', 'Update own profile'],
  ['patch', '/settings/thresholds', 'Update detection thresholds'],
  ['get', '/search', 'Global search'],
  ['post', '/ai/chat', 'Ask the operations assistant (grounded in tool results)'],
  ['get', '/ai/conversations', 'Assistant conversations'],
  ['post', '/ai/conversations', 'Create conversation'],
  ['get', '/ai/conversations/{id}', 'Conversation messages'],
  ['patch', '/ai/conversations/{id}', 'Rename conversation'],
  ['delete', '/ai/conversations/{id}', 'Delete conversation'],
  ['post', '/ai/query', 'Ask Your Data: validated structured query (no raw SQL)'],
  ['post', '/ai/query/export', 'CSV export of an Ask Your Data result'],
  ['get', '/simulator/status', 'Simulator status'],
  ['get', '/simulator/config', 'Simulator configuration'],
  ['post', '/simulator/start', 'Start simulator'],
  ['post', '/simulator/stop', 'Stop simulator'],
  ['post', '/simulator/reset', 'Reset simulator configuration'],
  ['patch', '/simulator/config', 'Update simulator rates'],
  ['post', '/simulator/scenario', 'Start a demo incident scenario'],
  ['post', '/simulator/scenario/resolve', 'End the active scenario'],
  ['post', '/dev/reset-demo', 'Reset demo data (development only)'],
]

const paths: Record<string, Partial<Record<Method, { summary: string; security?: [] }>>> = {}
for (const [method, path, summary] of ROUTES) {
  const key = `/api${path}`
  paths[key] = { ...paths[key], [method]: PUBLIC.has(`${method.toUpperCase()} ${path}`) ? { summary, security: [] } : { summary } }
}

export const openApi = {
  openapi: '3.0.3',
  info: {
    title: 'FinOpsX API',
    version: '2.0.0',
    description: 'Conceptual fintech operations API (demo environment). All data is synthetic. Not affiliated with or endorsed by F1Soft.',
  },
  components: {
    securitySchemes: { bearerAuth: { type: 'http', scheme: 'bearer', bearerFormat: 'JWT' } },
  },
  security: [{ bearerAuth: [] }],
  paths,
}
