export const openApi = {
  openapi: '3.0.3',
  info: {
    title: 'FinOpsX API',
    version: '1.0.0',
    description: 'Conceptual fintech operations API. All data is synthetic.',
  },
  components: {
    securitySchemes: { bearerAuth: { type: 'http', scheme: 'bearer', bearerFormat: 'JWT' } },
  },
  security: [{ bearerAuth: [] }],
  paths: {
    '/api/auth/login': { post: { summary: 'Login', security: [] } },
    '/api/auth/refresh': { post: { summary: 'Rotate refresh token', security: [] } },
    '/api/auth/logout': { post: { summary: 'Logout' } },
    '/api/dashboard/summary': { get: { summary: 'Dashboard aggregates' } },
    '/api/transactions': { get: { summary: 'Paginated transactions' } },
    '/api/transactions/{id}': { get: { summary: 'Transaction detail' } },
    '/api/institutions': { get: { summary: 'Institutions' } },
    '/api/institutions/{id}': { get: { summary: 'Institution detail' } },
    '/api/system/health': { get: { summary: 'System health' } },
    '/api/incidents': { get: { summary: 'Incidents' }, post: { summary: 'Create incident' } },
    '/api/incidents/{id}': { get: { summary: 'Incident detail' }, patch: { summary: 'Update incident' } },
    '/api/anomalies': { get: { summary: 'Anomalies' } },
    '/api/anomalies/{id}': { patch: { summary: 'Review anomaly' } },
    '/api/reports': { get: { summary: 'Reports' }, post: { summary: 'Generate report' } },
    '/api/reports/{id}/download': { get: { summary: 'Download PDF, CSV, or Excel' } },
    '/api/audit-logs': { get: { summary: 'Audit logs' } },
    '/api/users': { get: { summary: 'Users' }, post: { summary: 'Create user' } },
    '/api/ai/chat': { post: { summary: 'Ask the operations assistant' } },
    '/api/simulator/start': { post: { summary: 'Start simulator' } },
    '/api/simulator/stop': { post: { summary: 'Stop simulator' } },
    '/api/simulator/reset': { post: { summary: 'Reset simulator configuration' } },
    '/api/simulator/status': { get: { summary: 'Simulator status' } },
    '/api/simulator/scenario': { post: { summary: 'Start a demo incident scenario' } },
  },
}
